### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jinxx0** [jsac90/Fake-Email-Generator#1]
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: C:\Users\MNT\Desktop\Fake-Email-Generator-master\FakeRandomEmails.py
Traceback (most recent call last):
  File "C:\Users\MNT\Desktop\Fake-Email-Generator-master\FakeRandomEmails.py", line 37, in <module>
    howmany = getcount()
  File "C:\Users\MNT\Desktop\Fake-Email-Generator-master\FakeRandomEmails.py", line 10, in getcount
    rownums = raw_input("How many fake email addresses?: ")
NameError: name 'raw_input' is not defined
>>>

**Comment by asdat3** [comment]
just use input instead of raw_input

**Comment by asdat3** [comment]
old:
rownums = raw_input("How many fake email addresses?: ")
new:
rownums = input("How many fake email addresses?: ")

**Comment by jinxx0** [comment]
thanks
